### ISSUE TITLE
Quite impressed!

### ISSUE THREAD

**Issue by brian-lamb-software-engineer** [nathan-j-brenner/meanTodo#1]
I feel right at home in there. I haven't been able to look into any of the modules yet, but i see that indeed your using modules, which is really cool, and have a nice directory structure, and utilizing a package json, keeping it packaged, leveraging npm to pull down packages that you like to customize your app.  Too bad you didn't just fork my expressBuilder repo, and do all this work to that :-)  Or did you have this one up and running first.. You want to merge some code?  Not sure its even closely related actually, but great work, your well off on your way to be working directly for one of the sweeter enterprises up here, with a sweet cushy desk job in a hi-rise downtown PDX, or are you already there? lol.

**Comment by nathanBrenner** [comment]
Actually on my way to an interview.  The contract gig where I was writing html emails was ended (good terms, not enough work, at least that's what I was told).  A lot of this app is just from the treehouse course on building mean applications.  I had the front end angular part written for some recent code challenge for another gig, and I had been meaning to dig into writing rest apis, and adding tests, and webpack.  At some point I'll move everything over to typescript with ng1, and then ng2. I took some of the stuff that treehouse had done and refactored it from the conventions in John Papa's style guide.  Hope things are going well for you?

**Comment by brian-lamb-software-engineer** [comment]
Definitely, yeah for sure.  And there may be some angular opp coming up.  Our company is ever-merging, and some new apps may already be using this.

**Comment by nathanBrenner** [comment]
I just looked at your express builder.  It looks similar to the express generator.  Have you looked at that much? Or some of the other stuff from Yeoman? I had used the express generator at the code school, but it always felt like too much and I didn't know where to start. This thing was more focused so there's only stuff there that I actually needed and I could work iteratively on it.

**Comment by brian-lamb-software-engineer** [comment]
Yeah, mine is the express generator made simple, try it.  It’s nice..  it would be cool to know your feelings on it.  It spins up pretty nicely.
